import type { FunctionReference } from "convex/server";
import type {
  AppPlanActivation,
  AppPlanAssignment,
  BillingSnapshot,
  PlanCatalog,
  RecurringCycle,
  ScheduledSubscriptionUpdate,
} from "../../core/types.js";

export type { CheckoutIntent, PlanChangeIntent } from "../../core/types.js";

/**
 * UI-side permission flags for billing widgets.
 * Controls which buttons are enabled/visible. This is **cosmetic gating only** —
 * enforce real permissions server-side in your Convex functions.
 *
 * When a permission is `false`, the corresponding button renders as disabled.
 * When omitted or `undefined`, all actions default to enabled.
 */
export type BillingPermissions = {
  /** Allow creating new checkouts (subscribe / buy buttons). */
  canCheckout?: boolean;
  /** Allow switching plans or billing intervals. */
  canChangeSubscription?: boolean;
  /** Allow cancelling the active subscription. */
  canCancelSubscription?: boolean;
  /** Allow resuming a paused or scheduled-cancel subscription. */
  canResumeSubscription?: boolean;
  /** Allow changing the unit count on unit-based plans. */
  canUpdateUnits?: boolean;
  /** Allow opening the Creem customer billing portal. */
  canAccessPortal?: boolean;
};

/**
 * Backend function references for connected billing widgets.
 * Created once in your layout/page and passed to `<CreemConvexProvider>`.
 *
 * All references point to Convex functions generated by `creem.api({ resolve })`
 * or your own custom wrappers.
 *
 * @example
 * ```ts
 * const billingApi: ConnectedBillingApi = {
 *   uiModel: api.billing.uiModel,
 *   checkouts: { create: api.billing.checkoutsCreate },
 *   subscriptions: {
 *     update: api.billing.subscriptionsUpdate,
 *     cancel: api.billing.subscriptionsCancel,
 *     resume: api.billing.subscriptionsResume,
 *     cancelScheduledUpdate: api.billing.subscriptionsCancelScheduledUpdate,
 *   },
 *   customers: { portalUrl: api.billing.customersPortalUrl },
 * };
 * ```
 */
export type ConnectedBillingApi = {
  /** Query that returns the `ConnectedBillingModel` — called by all widgets to load billing state. */
  uiModel: FunctionReference<"query">;
  /** Checkout actions. */
  checkouts: {
    /** Create a checkout session and return `{ url }`. */
    create: FunctionReference<"action">;
  };
  /** Subscription mutation references. All optional — omit to hide the corresponding UI controls. */
  subscriptions?: {
    /** Plan switch or unit update mutation. */
    update?: FunctionReference<"mutation">;
    /** Cancel subscription mutation. */
    cancel?: FunctionReference<"mutation">;
    /** Resume paused/scheduled-cancel subscription mutation. */
    resume?: FunctionReference<"mutation">;
    /** Cancel an app-side period-end subscription update. */
    cancelScheduledUpdate?: FunctionReference<"mutation">;
  };
  /** Customer actions. */
  customers?: {
    /** Action that returns `{ url }` for the Creem billing portal. */
    portalUrl?: FunctionReference<"action">;
  };
  /** Transaction actions. */
  transactions?: {
    /** Action that returns paginated transaction history. */
    search?: FunctionReference<"action">;
  };
  /** Customer credits actions. */
  credits?: {
    /** Create a credits account for the current entity. */
    createAccount?: FunctionReference<"action">;
    /** Get current credit balance. */
    getBalance?: FunctionReference<"action">;
    /** Add credits to the account. */
    credit?: FunctionReference<"action">;
    /** Consume/spend credits from the account. */
    debit?: FunctionReference<"action">;
    /** List credit/debit history entries. */
    listEntries?: FunctionReference<"action">;
  };
  /** Optional app-owned plan activation mutation. */
  plans?: {
    /** Activate an app-owned catalog plan for the current billing entity. */
    activate?: FunctionReference<"mutation">;
  };
};

/** Product data as returned by the billing model query. Mirrors the Convex DB product schema. */
export type ConnectedProduct = {
  id: string;
  name?: string;
  description?: string;
  price?: number;
  currency?: string;
  billingType?: string;
  billingPeriod?: string;
  status?: string;
  taxMode?: string;
  taxCategory?: string;
  imageUrl?: string;
  features?: Array<{ id: string; description: string }>;
};

/**
 * Complete billing state returned by the `uiModel` query.
 * Consumed internally by all connected widgets — you typically don't need to access this directly.
 */
export type ConnectedBillingModel = {
  /** Authenticated user info, or `null` when unauthenticated (public pricing page). */
  user: {
    _id: string;
    email: string;
    isFree?: boolean;
    isTrialing?: boolean;
    trialEnd?: string | null;
  } | null;
  /** Optional server-resolved billing catalog. Used by connected widgets when the provider has no catalog. */
  catalog?: PlanCatalog | null;
  /** Billing state. `null` when unauthenticated. */
  snapshot: BillingSnapshot | null;
  /** All synced products from the Creem dashboard. */
  allProducts: ConnectedProduct[];
  /** Product IDs the entity has purchased (one-time orders). */
  ownedProductIds: string[];
  /** Product ID of the current subscription, or `null`. */
  subscriptionProductId: string | null;
  /** Explicit app-owned active free plan ID. `undefined` preserves the default widget fallback. */
  activeFreePlanId?: string | null;
  /** App-owned active plan ID. Prefer this over `activeFreePlanId` for trial/free/custom plans. */
  activePlanId?: string | null;
  /** Activation history for app-owned plans, used for once-per-entity eligibility. */
  appPlanActivations?: AppPlanActivation[];
  /** Current and scheduled assignments for app-owned plans. */
  appPlanAssignments?: AppPlanAssignment[];
  /** All active subscriptions with full details. */
  activeSubscriptions?: Array<{
    id: string;
    productId: string;
    status: string;
    cancelAtPeriodEnd: boolean;
    currentPeriodEnd: string | null;
    currentPeriodStart: string;
    units: number | null;
    recurringInterval: string | null;
    trialEnd?: string | null;
  }>;
  /** App-side period-end subscription updates that have not applied yet. */
  scheduledSubscriptionUpdates?: ScheduledSubscriptionUpdate[];
  /** Whether this entity has a Creem customer record (needed for billing portal). */
  hasCreemCustomer?: boolean;
  /** Reserved for future billing policy data. */
  policy?: unknown;
};

/**
 * Plan type for `<Subscription.Item>`.
 * - `"free"` — free tier, no checkout
 * - `"single"` — standard paid plan (flat pricing)
 * - `"unit-based"` — per-unit pricing with optional unit picker
 * - `"enterprise"` — "Contact sales" CTA, no checkout
 */
export type SubscriptionPlanType =
  | "free"
  | "single"
  | "unit-based"
  | "enterprise";

export type SubscriptionPlanRegistration = {
  planId: string;
  type?: SubscriptionPlanType;
  groupId?: string;
  groupTitle?: string;
  title?: string;
  description?: string;
  contactUrl?: string;
  recommended?: boolean;
  productIds?: Partial<Record<RecurringCycle, string>>;
};

export type SubscriptionGroupRegistration = {
  value: string;
  label: string;
  description?: string;
  plans: readonly string[];
};

export type ConnectedTransaction = {
  id: string;
  amount: number;
  amountPaid?: number | null;
  discountAmount?: number | null;
  currency: string;
  type: string;
  taxCountry?: string | null;
  taxAmount?: number | null;
  status: string;
  refundedAmount?: number | null;
  order?: string | null;
  subscription?: string | null;
  customer?: string | null;
  description?: string;
  periodStart?: number;
  periodEnd?: number;
  createdAt: number;
};

export type ConnectedPagination = {
  totalRecords: number;
  totalPages: number;
  currentPage: number;
  nextPage: number | null;
  prevPage: number | null;
};

export type ConnectedTransactionList = {
  items: ConnectedTransaction[];
  pagination: ConnectedPagination;
};

/**
 * Product type for `<Product.Item>`.
 * - `"one-time"` — purchased once, shows "Owned" badge after purchase
 * - `"recurring"` — can be purchased multiple times (consumable), no "Owned" badge
 */
export type ProductType = "one-time" | "recurring";

/**
 * Upgrade path rule for `<Product.Root transition={[...]}>`.
 * - `"direct"` — checkout uses the target product directly
 * - `"via_product"` — checkout uses a dedicated upgrade product (delta pricing)
 */
export type Transition =
  | { from: string; to: string; kind: "direct" }
  | {
      from: string;
      to: string;
      kind: "via_product";
      /** Creem product ID for the upgrade (e.g. a delta-priced "Basic → Premium" product). */
      viaProductId: string;
    };

export type ProductItemRegistration = {
  productId: string;
  type: ProductType;
  title?: string;
  description?: string;
};
