name: Preview Publish Approved Pull Requests

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    outputs:
      has-permissions: ${{ steps.checkPermissions.outputs.require-result }}
    steps:
      - name: Check permissions
        id: checkPermissions
        uses: actions-cool/check-user-permission@v2.4.0
        with:
          require: "write"

  publish:
    needs: check
    if: needs.check.outputs.has-permissions == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - uses: pnpm/action-setup@v6.0.8
        with:
          version: 11.1.2

      - name: Node setup
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "24.x"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Clean
        run: pnpm clean

      - name: Build
        run: pnpm build

      - name: Publish package preview
        run: pnpm exec pkg-pr-new publish
